apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: mariamwafik333/todo-app
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_URL
              value: mongodb://root:example@mongo:27017/
